@startuml Class Diagram for Twitter Clone

class User <<Entity>> { 
  + firstName     : String
  + lastName      : String
  + userName      : String
  + email         : String
  + password      : String
  + followings    : [User]
  + followers     : [User]
  + tweets        : [Tweet]
  + likedTweets   : [Tweet]
  + homePage      : HomePage

  - createHomePage()    : HomePage
  + tweet()
  + deleteTweet()
  + follow()
  + unfollow()
  + retweet()
  + undoRetweet()
  + like()
  + undoLike()
}

class Tweet <<Entity>> {
  + id            : Number  
  + creator       : User
  + content       : String
  + createTime    : Date

  - generateId()  : Number
}

class Retweet <<Entity>> {
  + id            : Number
  + creator       : User
  + content       : String
  + createTime    : Date
  + shareTime     : Date

  - generateId()  : Number
}

class HomePage <<Entity>> {
  + tweets        : [Tweet]
}

User *-- Tweet
User *-- HomePage
Tweet <|-- Retweet

@enduml