@startuml Class Diagram for Twitter Clone

class User <<Entity>> {
  + id                : Number 
  + firstName         : String
  + lastName          : String
  + username          : String
  + email             : String
  + password          : String
  + tweets            : [Tweet]
  + likedTweets       : [Tweet]
  + followings        : [User]
  + followers         : [User]
  + home              : Home

  - createHome()  : Home
  + tweet()
  + deleteTweet()
  + follow()
  + unfollow()
  + retweet()
  + undoRetweet()
  + like()
  + undoLike()
}

class Tweet <<Entity>> {
  + id            : Number  
  + creator       : User
  + content       : String
  + createTime    : Date
}

class Retweet <<Entity>> {
  + id            : Number
  + creator       : User
  + content       : String
  + createTime    : Date
  + shareTime     : Date
}

class Home <<Entity>> {
  + tweets        : [Tweet]
}

User *-- Tweet
User *-- Home
Tweet <|-- Retweet

@enduml